global using BuildingBlocks.CQRS;
global using Catalog.Api.Models;
global using Mapster;
global using MediatR;
global using Marten;
global using Microsoft.AspNetCore.Mvc;
global using Catalog.Api.Exceptions;
global using FluentValidation;
global using FluentValidation.Results;
